version: '3.8'

services:
  # ---------------------------------
  # 1. Redis Service (No change)
  # ---------------------------------
  redis-server:
    image: redis:7-alpine
    container_name: local-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  # ---------------------------------
  # 2. Express App Service (The crucial change)
  # ---------------------------------
  express-app:
    build: .
    container_name: express-web
    # --- IMPORTANT CHANGE HERE ---
    env_file:
      - .env
    # -----------------------------
    ports:
      - '8080:${PORT}'
    depends_on:
      - redis-server
    # volumes:
    #   - .:/usr/src/app

volumes:
  redis_data:
